### ISSUE TITLE
Admin UI for GeoFence rules

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#136]
### Description
Evoluzione geofence con interfaccia grafica semplificata mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/#/geofence-rules-manager)

- [x] MapStore 2 integrated rules editor
- [x] Attribute Read/Write
- [x] Distinguish between general rules, default rules, workspace and layer rules
- [ ] Spatial filter in rule editro details

connected to geosolutions-it/MapStore2#2772
connected to geosolutions-it/MapStore2#2773
connected to geosolutions-it/MapStore2#2774
connected to geosolutions-it/MapStore2#2777
connected to geosolutions-it/MapStore2#2878

**Comment by simboss** [comment]
before moving on I would want to review this mockup
