### ISSUE TITLE
Statistical Query Engine (Req  3.3.10)

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-C040#17]
- [x] **Thematic maps**: Several spatial aggregator levels, ability to create themas using the GeoServer sldService. blocked by #90
- [x]  **Charts** : We can reuse the current aggregation wps and reimplement the client-side part in MapStore2 - blocked by geosolutions-it/MapStore2#2324 and blocked by #89 
- [x]  **Manager** : A tool that allows to setup thematic maps and associated charts to publish. Should allow to setup the thematic map options (map style, charts, layers to use...). blocked by #91 
- [ ]   **RenderingTransformation Aggregate WPS** (WONTDO): The aggregate WPS process should be extended (or another one created for the purpose) to aggregate on spatial entities; these will be used for thematic maps. The idea is to create a WPS to use as Rendering Transformation or By Itself, that aggregates geometries, adding an attribute with aggregation result. This can be used for styling and to create tables/charts with data. blocked by #92
