### ISSUE TITLE
Test Deploy v 1.2.2

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#185]
Deploy in test for #184

Other needed work:

- [ ] create a branch c040 on MS2 github to the revision currently used in c040 MS2's project

- [x] Port there the fix provided with #184

- [x] Update the MS2's revision in c040 project using the c040 MS2's branch

- [x] Verify ie11 closes issue (requires #183)

- [x] Fix vulnerabilities issues in package.json (requires #186)
