### ISSUE TITLE
GeoServer Update to v2.16.2

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#261]
### Description
Update the current version of GeoServer from 2.13.1 to 2.16.2 (Test and Production environments).

**Comment by Gnafu** [comment]
Will update to 2.16.2 with the following plugins:
- Oracle 
- GDAL 
- WPS
- CSS 
- Control Flow 
- Monitor (core)
- Excel 
- CSW 
- GeoFence 
- QueryLayer (Cross Layer Filtering)
- DXF
- Authkey
- Printing 
Community:
- DDS

Another release (2.16.x) for the mapfish print jar is needed: https://github.com/geosolutions-it/mapfish-print/wiki

In the documentation I found the following lines:
- ```WPS - hazelcast ? Not for the moment``` : I will not include the Hazelcast plugin
- ```GetCapCache (should be ported and built by Nuno) Evaluate if is needed```: I will not include the GetCapCache plugin

**Comment by Gnafu** [comment]
SLDService was not listed in the doc, fixed.

NOTE: They are not using the Marlin renderer

**Comment by Gnafu** [comment]
done

**Comment by tdipisa** [comment]
Todo in Production

**Comment by randomorder** [comment]
Tomcat upgraded, still not working

**Comment by randomorder** [comment]
https://docs.google.com/document/d/1-VDOZV0WKOmgPwd4lPTJ2787eMbQ_ljiGVWyegPxq_k/edit#heading=h.9citl6k0i57s

Taken tomcat-dbcp.jar from an older Tomcat installation (7.0.72). Working now

**Comment by tdipisa** [comment]
@Gnafu a production deploy is needed

**Comment by Gnafu** [comment]
WIP:

- [x] Get MS production war from @MV88 
- [x] Backup GS DATA_DIR
- [ ] Backup MS DB
- [ ] Backup MS webapp
- [ ] Update Tomcat in geofe (GeoServer Master)
- [ ] Update of GeoServer Master including #276
- [ ] Update Tomcat in geobe1 (GeoServer Slave1)
- [ ] Update of GeoServer Slave1 including #276
- [ ] Update Tomcat in geofe (GeoServer Slave2)
- [ ] Update of GeoServer Slave2 including #276
- [ ] Update of MS in geofe

**Comment by Gnafu** [comment]
This update contained a custom tomcat installation:

- Tomcat 7.0.76 with the tomcat-dbcp.jar from Tomcat 7.0.72

It would be best if we can investigate why GeoServer Oracle connection pool fails with Tomcat 7.0.76 and eventually fix.

**Comment by tdipisa** [comment]
@Gnafu the Apache v7.x is quite dead, it seams that the problem does not appens with tomcat >= 8
