### ISSUE TITLE
Project Update to MapStore v2020.02.xx

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C040#301]
### Description
The MapStore revision need to be updated to the latest stable branch 2020.02.xx.

MapStore currently installed is enough recent. It is necessary to check if the existing customizations are properly working after the project update. Custom or client's specific extensions are the following **that will be checked during the PR review**:

- [ ] **Thematic Maps / Statistical Query Engine Update**: Not officially maintained. It is necessary to check it after the update (a reference map [here](https://mappe.comune.genova.it/MapStore2/#/viewer/openlayers/1000002291) in production environment). Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008457/scenario-snapshots/14592539/test-snapshots/19053266).

- [ ] **Integration with SPID** (italian authentication system for Public Administrations): to check after the update. Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008465/scenario-snapshots/14592553/test-snapshots/19053280).

- [ ] **GeoCollect embedded**: to check after the update. Hiptests are available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008459/scenario-snapshots/14592543/test-snapshots/19053270) and [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008464/scenario-snapshots/14592549/test-snapshots/19053276)

- [ ] **FeatureViewer**: to check after the update. Hiptest available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008466/scenario-snapshots/14592554/test-snapshots/19053281)

- [ ] **Public Works Plugin**: to check after the update. Hiptest is available [here](https://studio.cucumber.io/projects/47740/test-runs/421040/folder-snapshots/4008466/scenario-snapshots/14592555/test-snapshots/19053282)

### Other useful information (optional):

New Plugins present in 2020.02.00 release to enable also in this project

- **Application Context**: related config [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L762).
- **GeoStory**: related config [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L690) and [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L51).

New Categories need to be created during the first deploy in GeoStore DB:
- GEOSTORY
- CONTEXT
- TEMPLATE
- USERSESSION
