### ISSUE TITLE
General Review of other Maps

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2-C040#341]
Review also other maps of interests:
- [x] featured maps and dashboards
- [x] maps shown in the first page
- [x] maps more used (how do we know which are @randomorder, analytics ?)
- [x] other things at random

Things to check:
- too many layers checked on at first --> we might either uncheck some, zoom in or make some untiled to reduce the number of tiles called
- too many untiled layers --> make untiled those who have sparese data or many empty 
- layers not tile cached
- layers not  using the right formats --> vector overlays should be png8
- background not using the right formats --> e.g. BASE-CARTOGRAFICA not using JPEG
- thumbnails too bug in pixels dimensions, wrong format (use JPEG) and weight

The thumb for BASE-CARTOGRAFICA is attached below.
![bkg](https://user-images.githubusercontent.com/693880/99786173-75c83380-2b1e-11eb-97c8-1ee31a8180cd.jpg)

**Comment by ElenaGallo** [comment]
@simboss I reviewed the following 30 maps (they are half of the maps on the instance):

- RETI DEL SOTTOSUOLO
- WSO2
- EMERGENZA SANITARIA
- EMERGENZA NEVE - GELO
- SUE - SPORTELLO UNICO EDILIZIA
- Aree Verdi - DATI AD ACCESSO CONSENTITO DALLA RETE INTERNA
- Mobilità e fermate trasporto pubblico (AMT)
- EMERGENZA MORANDI
- Cerca il tuo seggio
- P.E.B.A - Piano di Eliminazione delle barriere architettoniche PEBA
- Mappatura fontanelle
- CLASSIFICAZIONE STATISTICAL ENGINE
- Protezione Civile per il cittadino
- CENSIMENTO SITI BUONI SPESA
- Telecamere pubbliche e private
- Settore Energia - DATI AD ACCESSO CONSENTITO DALLA RETE INTERNA
- Classificazione amministrativa delle strade del Comune di Genova
- Servizi derattizzazioni eseguite nei caseggiati - animali critici
- Mappa Eliminazione Barriere Architettoniche
- Catasto terreni e stampa carte tecniche 
- DIAGNOSI  ENERGETICA SCUOLE
- BOZZA Classificazione tecnico-funzionale delle strade del Comune di Genova
- Genova: le Strade nuove e il sistema dei Palazzi dei Rolli - sito UNESCO
- Interventi LLPP da luglio 2017
- Indicatori VAS del Piano Urbanistico Comunale - PUC
- BONIFICHE
- Geologia
- GEOMORFOLOGIA (GEOLOGIA)
- MICROZONIZZAZIONE SISMICA (GEOLOGIA)
- Commercio
- Piano Comunale di Emergenza - Protezione Civile- DATI AD ACCESSO CONSENTITO DALLA RETE INTERNA

**Comment by simboss** [comment]
@ElenaGallo thx, i would stop here for the moment.
